In [1]:
import  torch

张量表⽰⼀个由数值组成的数组，这个数组可能有多个维度。具有⼀个轴的张量对应数学上的向量（vector）；具有两个轴的张量对应数学上的矩阵（matrix）；具有两个轴以上的张量没有特殊的数学名称。

⾸先，我们可以使⽤ arange 创建⼀个⾏向量 x。这个⾏向量包含以0开始的前12个整数，它们默认创建为整数。也可指定创建类型为浮点数。张量中的每个值都称为张量的 元素（element）。

In [4]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

可以通过张量的shape属性来访问张量（沿每个轴的⻓度）的形状。也可以通过size来实现

In [13]:
x.shape

torch.Size([12])

In [14]:
x.size()

torch.Size([12])

如果只想知道张量中元素的总数，即形状的所有元素乘积，可以检查它的⼤⼩（size）。因为这⾥在处理的是⼀个向量，所以它的shape与它的size相同。

In [15]:
x.numel()

12

要想改变⼀个张量的形状⽽不改变元素数量和元素值，可以调⽤reshape函数。例如，可以把张量x从形状为
（12,）的⾏向量转换为形状为（3,4）的矩阵。这个新的张量包含与转换前相同的值，但是它被看成⼀个3⾏4列
的矩阵。要重点说明⼀下，虽然张量的形状发⽣了改变，但其元素值并没有变。注意，通过改变张量的形状，
张量的⼤⼩不会改变。

In [16]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [18]:
X.shape

torch.Size([3, 4])

In [19]:
X.size()

torch.Size([3, 4])

In [20]:
X.numel()

12

我们不需要通过⼿动指定每个维度来改变形状。也就是说，如果我们的⽬标形状是（⾼度,宽度），那么在
知道宽度后，⾼度会被⾃动计算得出，不必我们⾃⼰做除法。在上⾯的例⼦中，为了获得⼀个3⾏的矩阵，
我们⼿动指定了它有3⾏和4列。幸运的是，我们可以通过-1来调⽤此⾃动计算出维度的功能。即我们可以
⽤x.reshape(-1,4)或x.reshape(3,-1)来取代x.reshape(3,4)。


In [21]:
x.reshape(-1,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [22]:
x.reshape(3,-1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

有时，我们希望使⽤全0、全1、其他常量，或者从特定分布中随机采样的数字来初始化矩阵。我们可以创建
⼀个形状为（2,3,4）的张量，其中所有元素都设置为0，1。代码如下：

In [23]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [24]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

有时我们想通过从某个特定的概率分布中随机采样来得到张量中每个元素的值。例如，当我们构造数组来作
为神经⽹络中的参数时，我们通常会随机初始化参数的值。以下代码创建⼀个形状为（3,4）的张量。其中的
每个元素都从均值为0、标准差为1的标准⾼斯分布（正态分布）中随机采样。

In [25]:
torch.randn(3,4)

tensor([[ 0.0215, -0.7058,  0.9474, -0.6352],
        [-0.1501,  0.4661, -1.2103,  0.3463],
        [-0.1884, -0.2575,  0.9395,  0.8489]])

我们还可以通过提供包含数值的Python列表（或嵌套列表），来为所需张量中的每个元素赋予确定值。在这
⾥，最外层的列表对应于轴0，内层的列表对应于轴1。

In [26]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

对于任意具有相同形状的张量，常⻅的标准算术运算符（+、-、*、/和**）都可以被升级为按元素运算。我
们可以在同⼀形状的任意两个张量上调⽤按元素操作。

In [4]:
import torch
x = torch.tensor([1.0,2,3,4])
y = torch.tensor([2,2,2,2])
x + y, x - y ,x * y ,x / y, x ** y,torch.exp(x)

(tensor([3., 4., 5., 6.]),
 tensor([-1.,  0.,  1.,  2.]),
 tensor([2., 4., 6., 8.]),
 tensor([0.5000, 1.0000, 1.5000, 2.0000]),
 tensor([ 1.,  4.,  9., 16.]),
 tensor([ 2.7183,  7.3891, 20.0855, 54.5981]))

以把多个张量连结（concatenate）在⼀起，把它们端对端地叠起来形成⼀个更⼤的张量。我们只需
要提供张量列表，并给出沿哪个轴连结。下⾯的例⼦分别演⽰了当我们沿⾏（轴-0，形状的第⼀个元素）和按
列（轴-1，形状的第⼆个元素）连结两个矩阵

In [5]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

有时，我们想通过逻辑运算符构建⼆元张量。以X == Y为例：对于每个位置，如果X和Y在该位置相等，则新
张量中相应项的值为1。这意味着逻辑语句X == Y在该位置处为真，否则该位置为0。

In [6]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素进⾏求和，会产⽣⼀个单元素张量

In [7]:
X.sum()

tensor(66.)

### 2.1.3 广播机制
在上⾯的部分中，我们看到了如何在相同形状的两个张量上执⾏按元素操作。在某些情况下，即使形状不同，
我们仍然可以通过调⽤ ⼴播机制（broadcasting mechanism）来执⾏按元素操作。这种机制的⼯作⽅式如
下：
1. 通过适当复制元素来扩展⼀个或两个数组，以便在转换之后，两个张量具有相同的形状；
2. 对⽣成的数组执⾏按元素操作。

在⼤多数情况下，我们将沿着数组中⻓度为1的轴进⾏⼴播，如下例⼦

In [8]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

由于a和b分别是3 × 1和1 × 2矩阵，如果让它们相加，它们的形状不匹配。我们将两个矩阵⼴播为⼀个更⼤
的3 × 2矩阵，如下所⽰：矩阵a将复制列，矩阵b将复制⾏，然后再按元素相加。

In [9]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.1.4索引和切⽚  
就像在任何其他Python数组中⼀样，张量中的元素可以通过索引访问。与任何Python数组⼀样：第⼀个元素
的索引是0，最后⼀个元素索引是-1；可以指定范围以包含第⼀个元素和最后⼀个之前的元素。
如下所⽰，我们可以⽤[-1]选择最后⼀个元素，可以⽤[1:3]选择第⼆个和第三个元素：

In [10]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

以通过指定索引来将元素写⼊矩阵

In [11]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

如果我们想为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值。例如，[0:2, :]访问
第1⾏和第2⾏，其中“:”代表沿轴1（列）的所有元素。虽然我们讨论的是矩阵的索引，但这也适⽤于向量
和超过2个维度的张量。

In [13]:
X[0:2,:]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 2.1.5 节省内存
运⾏⼀些操作可能会导致为新结果分配内存。例如，如果我们⽤Y = X + Y，我们将取消引⽤Y指向的张量，
⽽是指向新分配的内存处的张量。
在下⾯的例⼦中，我们⽤Python的id()函数演⽰了这⼀点，它给我们提供了内存中引⽤对象的确切地址。运
⾏Y = Y + X后，我们会发现id(Y)指向另⼀个位置。这是因为Python⾸先计算Y + X，为结果分配新的内存，
然后使Y指向内存中的这个新位置。

In [15]:
before = id(Y)
Y = Y + X
id(Y) == before

False

频繁更换数组的存储位置这可能是不可取的，原因有两个：
1. ⾸先，我们不想总是不必要地分配内存。在机器学习中，我们可能有数百兆的参数，并且在⼀秒内多次
更新所有参数。通常情况下，我们希望原地执⾏这些更新；
2. 如果我们不原地更新，其他引⽤仍然会指向旧的内存位置，这样我们的某些代码可能会⽆意中引⽤旧
的参数。

幸运的是，执⾏原地操作⾮常简单。我们可以使⽤切⽚表⽰法将操作的结果分配给先前分配的数组，例如Y[:]
=expression。为了说明这⼀点，我们⾸先创建⼀个新的矩阵Z，其形状与另⼀个Y相同，使⽤zeros_like来
分配⼀个全0的块。

In [19]:
Z = torch.zeros_like(Y)
print('before id(Z):',id(Z))
Z[:] = X + Y
print('after id(Z):',id(Z))

before id(Z): 2589730722256
after id(Z): 2589730722256


如果在后续计算中没有重复使⽤X，我们也可以使⽤X[:] = X + Y或X += Y来减少操作的内存开销。

In [23]:
before = id(X)
X += Y
id(X) == before

True

### 2.1.6 转换为其他Python对象
将深度学习框架定义的张量转换为NumPy张量（ndarray）很容易，反之也同样容易。torch张量和numpy数
组将共享它们的底层内存，就地操作更改⼀个张量也会同时更改另⼀个张量。

In [25]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

要将⼤⼩为1的张量转换为Python标量，我们可以调⽤item函数或Python的内置函数。

In [26]:
a = torch.tensor([3.0])
a,a.item(), float(a), int(a)

(tensor([3.]), 3.0, 3.0, 3)

练习
1. 运⾏本节中的代码。将本节中的条件语句X == Y更改为X < Y或X > Y，然后看看你可以得到什么样的
张量。
2. ⽤其他形状（例如三维张量）替换⼴播机制中按元素操作的两个张量。结果是否与预期相同？


In [27]:
X < Y, X > Y

(tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [39]:
a = torch.ones((3,2,1))
b = torch.ones(1,1,3)
a,b,a + b

(tensor([[[1.],
          [1.]],
 
         [[1.],
          [1.]],
 
         [[1.],
          [1.]]]),
 tensor([[[1., 1., 1.]]]),
 tensor([[[2., 2., 2.],
          [2., 2., 2.]],
 
         [[2., 2., 2.],
          [2., 2., 2.]],
 
         [[2., 2., 2.],
          [2., 2., 2.]]]))